### ISSUE TITLE
White border on light and dark theme

### ISSUE THREAD

**Issue by ghost** [diedummydie/Safari-Theme-for-Firefox#16]
Hi, 

There is an issue with both Dark and Light themes where a black or white line appears as a divider. (Latest theme version and Firefox 70.0)

Thank you

![imagen](https://user-images.githubusercontent.com/31588962/68589204-97aec500-048b-11ea-8386-f22078831fc7.png)
![imagen](https://user-images.githubusercontent.com/31588962/68589222-a39a8700-048b-11ea-81d4-9e8656312eda.png)

**Comment by diedummydie** [comment]
I see that now when layout is in 'normal' density. Thanks for pointing this out. The separator doesn't show up in compact density, and the padding between buttons is more Safari-like in compact density too. That's my fault because I've been working only in compact while creating this.

You can select compact density by right-clicking an empty spot on the toolbar, selecting 'customize', and then 'density'.

I'm adding a fix for normal now though. Thanks again.

**Comment by ghost** [comment]
No problem, Thank you and congrats on your work. I’ll be adding more ideas and issues in the future.
