### ISSUE TITLE
Full screen breaks theme (increased padding)

### ISSUE THREAD

**Issue by clo4** [diedummydie/Safari-Theme-for-Firefox#2]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/52195359/67610388-26f68000-f7de-11e9-9b5e-c80b54e1e427.png">

Removing [this line](https://github.com/diedummydie/Safari-Theme-for-Firefox/blob/8e401b83449d850e195d1c2049b9d5cafbb944c8/chrome/hide_tabs_with_one_tab.css#L42) fixes the problem.

**Comment by diedummydie** [comment]
Thanks! I made that change in [eae2797](https://github.com/diedummydie/Safari-Theme-for-Firefox/commit/eae27977bf272bf6427b42bcb88452fc1a6cfbad).  

How do you get to that view? When I click the maximize button I get fullscreen mode rather than a traditional maximize, and that hides the window controls unless I hold the mouse at the top edge of the screen. In the menu I have 'View > Enter Full Screen' and 'Window > Minimize', but no verbatim 'maximize' option. Are you on the new 10.15 Catalina update or an older release?  

_(I'm staying with 10.14.x Mojave until Jan. 2020 when we'll find out how draconian the new restrictions on 3rd party software will be.)_

**Comment by clo4** [comment]
Ah, sorry for the late reply! Hovering over the traffic lights and holding <kbd>option</kbd> allows you to maximize the window in its current desktop, rather than moving it to its own! I'm using Catalina at the moment, though iirc the shortcut has been around for a few versions

**Comment by diedummydie** [comment]
Oh that's useful. I knew you could long press for iOS style split screen, but maximizing is something I may actually use. 

I fixed some `[inFullscreen="true"]` positioning issues as a result of my misunderstanding, and I'm about to push more `[sizemode="maximized"]` positioning fixes too for a regression I created at some point.
